### PR TITLE
Added Forgot Password #456

### PR DESCRIPTION
**Pull request by Mdraza78**
I've solved all the conflict!

### CODE REVIEW

**Comment by Mdraza78** [comment]
image

**Comment by Trisha-tech** [comment]
> I've solved all the conflict!

Kindly specify issue no you are addressing

**Comment by Trisha-tech** [comment]
> I've solved all the conflict!

Kindly specify issue no you are addressing

**Comment by Trisha-tech** [comment]
> I've solved all the conflict!

Kindly specify issue no you are addressing

**Comment by Mdraza78** [comment]
fix #456

**Comment by Trisha-tech** [comment]
> fix #300

I am asking about the issue no not pr no. @Mdraza78

**Comment by Mdraza78** [comment]
@Trisha-tech  updated

**Comment by Mdraza78** [comment]
@Trisha-tech please assign me the level

**Comment by Mdraza78** [comment]
@Trisha-tech please assign me the level

**Pull request merged**
