### PR TITLE
added cancel and returns page

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Trisha-tech 
I have added a page for cancellation and returns successfully
Kindly check it out

https://github.com/user-attachments/assets/dbd76e55-aa4c-405e-b36b-01956075d52d

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@Trisha-tech could you please review it

**Comment by Suman373** [comment]
> @Trisha-tech could you please review it

Create an issue first regarding this. We will assign it to you and then merge your PR.

**Comment by AswaniBolisetti** [comment]
@Trisha-tech 
I have created issue before #504 , and I was assigned and now I created this PR

**Comment by AswaniBolisetti** [comment]
@Trisha-tech 
could you please review and merge it

**Comment by Suman373** [comment]
> @Trisha-tech I have created issue before #504 , and I was assigned and now I created this PR

You could have tagged me or quoted to my reply instead. There is a PR template which every contributor has to follow. You did not so I wasn't sure if an issue was already created. Well am assigning this to you with labels. The PA will verify and merge it. Nice work !

**Review by Trisha-tech — APPROVED** [review]

**Pull request merged**
