### PR TITLE
Customer profile UI 

### LINKED ISSUE #358: [Bug]: Customer Profile UI Sidebar Not Functional and Some Details are Missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The side bar is having tabs like profile info, address PAN card. Some tabs are missing like the PAN card and Saved UPI. I only designed this UI so I can work on it further and make it functional.
 

### Expected behavior

I will be adding a form where user can fill its PAN card info.
I will be adding a form to buy gift cards
Gift cards can be a strategic marketing and sales tool for e-commerce businesses, and can help to increase sales and profits

### Add ScreenShots

image
When we click on PAN card it shows personal info.

I am gonna make it something like this
image

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by CodexRaunak**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds forms for PAN card information and saved UPI details..
  - Fixes the missing tabs in the customer profile UI sidebar
  - Updates the sidebar to make it functional.

###  Issues
-  "Fixes #358"

### Changes
List the detailed changes made in this PR.
- Added a new feature to include forms for entering PAN card and UPI details.
- Fixed the bug where tabs were not functional.

https://github.com/user-attachments/assets/e5255960-3947-4362-807c-876cd895bec8

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by CodexRaunak** [comment]
@Trisha-tech please review the PR and tell if any changes have to be made

**Comment by Trisha-tech** [comment]
> ### Description
> A clear and concise description of what the PR does.
> 
> * This PR does the following:
>   
>   * Adds forms for PAN card information and saved UPI details..
>   * Fixes the missing tabs in the customer profile UI sidebar
>   * Updates the sidebar to make it functional.
> 
> ### Issues
> * "Fixes [[Bug]: Customer Profile UI Sidebar Not Functional and Some Details are Missing #358](https://github.com/Trisha-tech/OnlineBookSales/issues/358)"
> 
> ### Changes
> List the detailed changes made in this PR.
> 
> * Added a new feature to include forms for entering PAN card and UPI details.
> * Fixed the bug where tabs were not functional.
> 
>  Customer-Profile.mp4 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly resolve these conflicts @CodexRaunak 
Fixed Search Function to Notify Users of Empty Input and No Matching Books by darshinihoney · Pull Request #476 · Trisha-tech_OnlineBookSales - Google Chrome 10_22_2024 2_27_38 PM

**Comment by CodexRaunak** [comment]
@Trisha-tech I fixed the conflicts , its good to go now

**Comment by Trisha-tech** [comment]
> @Trisha-tech I fixed the conflicts , its good to go now

Conflicts are still there.
Customer profile UI by CodexRaunak · Pull Request #563 · Trisha-tech_OnlineBookSales - Google Chrome 10_29_2024 3_52_43 PM

**Comment by CodexRaunak** [comment]
check now @Trisha-tech 
image

**Pull request merged**
