### PR TITLE
Revert "Added the wishlist section(both frontend + backend)"

### PR DESCRIPTION
**Pull request by Trisha-tech**
Reverts Trisha-tech/OnlineBookSales#206

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@Trisha-tech Please merge this...

**Comment by arunimaChintu** [comment]
@Trisha-tech Please merge this

**Comment by Trisha-tech** [comment]
> @Trisha-tech Please merge this

@arunimaChintu , Resolve the conflicts

**Comment by Trisha-tech** [comment]
> > @Trisha-tech Please merge this
> 
> @arunimaChintu , Resolve the conflicts

Resolve these conflicts @arunimaChintu 
Added home in navbar redirecting to home by arunimaChintu · Pull Request #205 · Trisha-tech_OnlineBookSales - Google Chrome 7_30_2024 10_01_32 PM

**Pull request closed without merging**
