### PR TITLE
Added book info page

### LINKED ISSUE #12: Add Detail Page as the User Clicks on the Book
I would like to work on the design when a user clicks a particular book the details of the book could be viewed
-Book Thumbnail
-About the author
-Title of the Book
-Price of the Book with a selection of currencies
-Quantity
-Add to Cart
-Reviews from the Readers
-Book Suggestions

### PR DESCRIPTION
**Pull request by Sourabh782**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ...
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder:  Fixes #12 

### Changes
List the detailed changes made in this PR.
- Added a new feature to ... view book page
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)

https://github.com/user-attachments/assets/eacc3e52-a95d-4479-a60a-b0b1927efb53

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@Sourabh782 Hey ! Nice work ! 👍
I think the book image can be made wider to improve the ratio as it looks thinner when compared to the details part.

**Comment by Sourabh782** [comment]
> @Sourabh782 Hey ! Nice work ! 👍 I think the book image can be made wider to improve the ratio as it looks thinner when compared to the details part.

Sure I tried it, but size was not increasing, still I'll look into it

**Comment by Suman373** [comment]
> > @Sourabh782 Hey ! Nice work ! 👍 I think the book image can be made wider to improve the ratio as it looks thinner when compared to the details part.
> 
> Sure I tried it, but size was not increasing, still I'll look into it

Why was it not increasing ?

**Comment by Sourabh782** [comment]
@Suman373 i have fixed that issue also fixed responsiveness issue :
Screenshot 2024-10-23 204506
Screenshot 2024-10-23 204455

**Comment by Sourabh782** [comment]
> @Sourabh782 Great work ! 🙌 I hope all the other images are looking like this. @Trisha-tech verify and merge this.

Yes the images src are added at image so all are working, I can share video of it

**Comment by Suman373** [comment]
> > @Sourabh782 Great work ! 🙌 I hope all the other images are looking like this. @Trisha-tech verify and merge this.
> 
> Yes the images src are added at image so all are working, I can share video of it

Not necessary !

**Comment by Sourabh782** [comment]
@Trisha-tech  can you check this pr?

**Comment by Trisha-tech** [comment]
> @Trisha-tech can you check this pr?

Kindly look into this once, details  of the  book are not showing. @Sourabh782

**Comment by Sourabh782** [comment]
> > @Trisha-tech can you check this pr?
> 
> Kindly look into this once, details of the book are not showing. @Sourabh782

Can you share ss?

**Pull request merged**
