### PR TITLE
Have done some enhancements in the CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by milansamuel609**
### Description
Done some enhancements in the CONTRIBUTING.md file

### Related Issues

-----------------------

### Changes
List the detailed changes made in this PR.

Section Title Changes: Updated section titles for consistency and clarity, such as "Getting Started," "Forking and Cloning the Repository," and "Making Changes."

Added GitHub Desktop Contribution Steps: Included a detailed section for contributing using GitHub Desktop, outlining the steps to clone the repository, make changes, commit, push, and create a pull request.

Revised Formatting: Improved formatting for better readability, such as clear headings and bullet points.

Guidelines Emphasis: Strengthened the emphasis on reporting issues and submitting pull requests, highlighting the importance of checking existing issues and writing clear commit messages.

Clarity in Steps: Clarified and organized the steps for both command line and GitHub Desktop contributions, ensuring that users can easily follow the instructions.

Added Encouragement: Included a section encouraging users to support the project by giving it a star on GitHub.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
It will help the user to easily understand anything related to contribution they have to do.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@milansamuel609 Which issue does this PR refer to ?

**Comment by milansamuel609** [comment]
> @milansamuel609 Which issue does this PR refer to ?

Actually I have just done some non coded contribution through documentation. Just that. I don't know it will be counted as a issue or not 😐

**Comment by Suman373** [comment]
> > @milansamuel609 Which issue does this PR refer to ?
> 
> Actually I have just done some non coded contribution through documentation. Just that. I don't know it will be counted as a issue or not 😐

You have to create an issue first and then get assigned to it. So, create an issue regarding documentation update and then we will assign it to you.

**Comment by Suman373** [comment]
@milansamuel609 Also you have to provide some screenshots for the changes you have made especially in the markdown file such that is provides better clarity and appearance.

**Comment by milansamuel609** [comment]
> @milansamuel609 Also you have to provide some screenshots for the changes you have made especially in the markdown file such that is provides better clarity and appearance.

Once again I will raise the PR.

**Comment by Suman373** [comment]
> > @milansamuel609 Also you have to provide some screenshots for the changes you have made especially in the markdown file such that is provides better clarity and appearance.
> 
> Once again I will raise the PR.

There is no need to close this one. You could have created an issue and referred the # here.

**Pull request closed without merging**
