### PR TITLE
chatbot added and its working!✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### Description
i have added the chatbot and its working perfectly fine. issue  #381 solved 

https://github.com/user-attachments/assets/a2156917-101d-4c33-8924-430908734c4a

@Trisha-tech can you please review this tech.
thank you!

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this thank you!

**Comment by Trisha-tech** [comment]
> ### Description
> i have added the chatbot and its working perfectly fine. issue #381 solved
> 
>  Screen.Recording.2024-10-11.at.12.15.16.AM.mov 
> @Trisha-tech can you please review this tech. thank you!
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Where does the homepage of the website? Not showing in the video. @T-Rahul-prabhu-38

**Comment by T-Rahul-prabhu-38** [comment]
ohhh shit
i added the wrong video
gimme some time ill find it , 2mins

**Comment by T-Rahul-prabhu-38** [comment]
https://github.com/user-attachments/assets/495c300f-3806-40bc-af80-3b22c22f4405

**Comment by T-Rahul-prabhu-38** [comment]
this was the right video.

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech  the correct video has been uploaded,sorry for the confusion

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this PR

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this PR

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this PR

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this PR

**Comment by T-Rahul-prabhu-38** [comment]
@Trisha-tech can you please review this PR.  this PR was made 3 days ago . it will be helpful if u can review this.

**Comment by T-Rahul-prabhu-38** [comment]
thank you!

**Pull request merged**
