### PR TITLE
added troubleshooting section to the readme file

### LINKED ISSUE #576: [Documentation Update]: Add a Troubleshooting Section to README
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to suggest adding a troubleshooting section to the README file. This section can help users resolve common issues they might encounter while running the application.

### Suggested Change

Potential topics could include:

- Common installation issues
- Problems with starting the server
- Issues related to dependencies
- FAQs

### Rationale

_No response_

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by vaishnavipal1869**
### Description
This PR does the following:
- Adds a troubleshooting section to the README file to assist users with common issues encountered during installation and server setup.
- Provides FAQs to address frequent questions regarding the local database and support contact.

### Related Issues
- Fixes #576 

### Changes
List the detailed changes made in this PR:
- Added a new troubleshooting section covering:
  - Common installation issues
  - Problems with starting the server
  - Issues related to dependencies
  - Frequently asked questions (FAQs)

### Testing Instructions
Detailed instructions on how to test the changes:
1. Pull this branch.
2. Check out the README file to review the newly added troubleshooting section.
3. Ensure that the troubleshooting instructions accurately reflect common issues and provide clear resolutions.

### Screenshots (if applicable)
- not applicable.

### Additional Context
- This PR is based on the feedback received from users facing installation issues. The added troubleshooting section aims to streamline the onboarding process and reduce confusion for new users.

### Checklist
Make sure to check off all the items before submitting:
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I am working on this issue under GSSOC.

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> ### Description
> This PR does the following:
> 
> * Adds a troubleshooting section to the README file to assist users with common issues encountered during installation and server setup.
> * Provides FAQs to address frequent questions regarding the local database and support contact.
> 
> ### Related Issues
> * Fixes [[Documentation Update]: Add a Troubleshooting Section to README #576](https://github.com/Trisha-tech/OnlineBookSales/issues/576)
> 
> ### Changes
> List the detailed changes made in this PR:
> 
> * Added a new troubleshooting section covering:
>   
>   * Common installation issues
>   * Problems with starting the server
>   * Issues related to dependencies
>   * Frequently asked questions (FAQs)
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes:
> 
> 1. Pull this branch.
> 2. Check out the README file to review the newly added troubleshooting section.
> 3. Ensure that the troubleshooting instructions accurately reflect common issues and provide clear resolutions.
> 
> ### Screenshots (if applicable)
> * not applicable.
> 
> ### Additional Context
> * This PR is based on the feedback received from users facing installation issues. The added troubleshooting section aims to streamline the onboarding process and reduce confusion for new users.
> 
> ### Checklist
> Make sure to check off all the items before submitting:
> 
> * [x]  I have performed a self-review of my code.
> * [x]  I have commented on my code, particularly in hard-to-understand aras.
> * [x]  My changes generate no new warnings.
> * [x]  I am working on this issue under GSSOC.

Kindly add some screenshot or screen recording of the features you have added. @vaishnavipal1869

**Comment by Suman373** [comment]
@vaishnavipal1869 Add a screenshot of the troubleshooting section you have added in the markdown file.

**Comment by vaishnavipal1869** [comment]
> @vaishnavipal1869 Add a screenshot of the troubleshooting section you have added in the markdown file.

hello @Suman373 , Since my changes were purely related to documentation, I believe a screenshot may not be necessary in this case. However, if a screenshot is still required, I can provide one of the README file showing the updates. Please let me know how you'd prefer to proceed.

**Comment by Suman373** [comment]
> > @vaishnavipal1869 Add a screenshot of the troubleshooting section you have added in the markdown file.
> 
> hello @Suman373 , Since my changes were purely related to documentation, I believe a screenshot may not be necessary in this case. However, if a screenshot is still required, I can provide one of the README file showing the updates. Please let me know how you'd prefer to proceed.

Although you have made documentation changes, a screenshot for the updated markdown file especially your changes is necessary. I have checked it so you don't have to update the PR but make sure to add it from next time onwards. Anyway, nice work ! We look forward to more contributions from your side 👍

**Comment by Suman373** [comment]
@Trisha-tech you may verify and merge it 

image

**Comment by vaishnavipal1869** [comment]
> > > @vaishnavipal1869 Add a screenshot of the troubleshooting section you have added in the markdown file.
> > 
> > 
> > hello @Suman373 , Since my changes were purely related to documentation, I believe a screenshot may not be necessary in this case. However, if a screenshot is still required, I can provide one of the README file showing the updates. Please let me know how you'd prefer to proceed.
> 
> Although you have made documentation changes, a screenshot for the updated markdown file especially your changes is necessary. I have checked it so you don't have to update the PR but make sure to add it from next time onwards. Anyway, nice work ! We look forward to more contributions from your side 👍

Apologies for not including the screenshots earlier. If you'd like, I can add them right away—just let me know how you'd like me to proceed. I appreciate the feedback and will make sure to include them in future updates

**Comment by Suman373** [comment]
> > > > @vaishnavipal1869 Add a screenshot of the troubleshooting section you have added in the markdown file.
> > > 
> > > 
> > > hello @Suman373 , Since my changes were purely related to documentation, I believe a screenshot may not be necessary in this case. However, if a screenshot is still required, I can provide one of the README file showing the updates. Please let me know how you'd prefer to proceed.
> > 
> > 
> > Although you have made documentation changes, a screenshot for the updated markdown file especially your changes is necessary. I have checked it so you don't have to update the PR but make sure to add it from next time onwards. Anyway, nice work ! We look forward to more contributions from your side 👍
> 
> Apologies for not including the screenshots earlier. If you'd like, I can add them right away—just let me know how you'd like me to proceed. I appreciate the feedback and will make sure to include them in future updates

Its okay ! 😊

**Pull request merged**
