### PR TITLE
Issue #259 - Added routes for each categories in the Book Categories section and created blank pages for each of the pages

### LINKED ISSUE #259: Create routes and pages for Book Categories
As of now, the categories Book Categories section do not route to any page when clicked. I would like to create blank pages for now ( or maybe do some simple designed pages) for each of these categories so that when it is clicked it is routed to those pages.

### PR DESCRIPTION
**Pull request by Lanaanvar**
…reated blank pages for each of them

### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds routes for each categories in the Book Categories section and created blank pages for each.

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Fixes #259 

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Lanaanvar** [comment]
I missed the last point in the checklist. I am working on this issue under GSSOC'24 ext.

**Comment by Trisha-tech** [comment]
> …reated blank pages for each of them
> 
> ### Description
> A clear and concise description of what the PR does.
> 
> * This PR does the following:
>   
>   * Adds routes for each categories in the Book Categories section and created blank pages for each.
> 
> ### Related Issues
> Link any related issues using the format `Fixes #issue_number`. This helps to automatically close related issues when the PR is merged.
> 
> * Placeholder: "Fixes [Added workflow for closing old PRs  #123](https://github.com/Trisha-tech/OnlineBookSales/pull/123)"
> 
> ### Changes
> List the detailed changes made in this PR.
> 
> * Added a new feature to ...
> * Refactored the ...
> * Fixed a bug in ...
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Run `npm install` to install dependencies.
> 3. Run `npm test` to execute the test suite.
> 4. Verify that ...
> 
> ### Screenshots (if applicable)
> Add any screenshots that help explain or visualize the changes.
> 
> ### Additional Context
> Any additional context or information that reviewers should be aware of.
> 
> * This PR is based on the following...
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x ] I am working on this issue under GSSOC

Kindly add the issue no you are addressing @Lanaanvar

**Review by Suman373 — CHANGES_REQUESTED** [review]
Please add some screenshots of the changes/features you have implemented.

**Comment by Trisha-tech** [comment]
> Please add some screenshots of the changes/features you have implemented.

Also kindly resolve these conflicts @Lanaanvar 
Added forgot password feature by Mdraza78 · Pull Request #300 · Trisha-tech_OnlineBookSales - Google Chrome 10_5_2024 1_15_47 PM

**Comment by Lanaanvar** [comment]
Ok I will

**Comment by Suman373** [comment]
@Lanaanvar look into the requested changes and then we can merge your branch.

**Comment by Lanaanvar** [comment]
ok

**Comment by Lanaanvar** [comment]
> Please add some screenshots of the changes/features you have implemented.

image
image
image
image

The same way, blank pages are created for all categories in the section

**Review by Suman373 — APPROVED** [review]
Thanks for the screenshots. Great work ! @Lanaanvar

**Comment by Lanaanvar** [comment]
Thank You

**Pull request merged**
