### PR TITLE
Adds the OrdersPage [frontend + backend]

### LINKED ISSUE #200: [Feature Request]: Create Orders Page[FRONTEND + BACKEND]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creates Orders Page[FRONTEND + BACKEND]

### Use Case

Creates Orders Page[FRONTEND + BACKEND]

### Benefits

Creates Orders Page[FRONTEND + BACKEND]

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by arunimaChintu**
### Description
Closes #200 
- This PR does the following:
  - Adds ... the Orders Page[frontend + backend]
  - Fixes #200 
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #200 "

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> @Trisha-tech please please merge this...

Resolve these conflicts @arunimaChintu 
screenshot-github com-2024 07 08-23_28_24

**Comment by arunimaChintu** [comment]
@Trisha-tech done...

**Comment by arunimaChintu** [comment]
@Trisha-tech I have resolved the conflicts... Please merge this now

**Comment by arunimaChintu** [comment]
@Trisha-tech Please merge this soon... Tomorrow is the last date for gssoc24

**Comment by arunimaChintu** [comment]
@Trisha-tech would you please mind to add the labels... Please

**Pull request merged**
