### PR TITLE
Added router for page navigation

### PR DESCRIPTION
**Pull request by ArtiGaund**
If there is any problem with it, then inform me.

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> If there is any problem with it, then inform me.

Added router for page navigation by ArtiGaund · Pull Request #63 · Trisha-tech_OnlineBookSales - Google Chrome 5_13_2024 11_38_41 AM

Resolve these conflicts

**Comment by ArtiGaund** [comment]
Is there still problem here?

**Comment by sanjay-kv** [comment]
@Trisha-tech im PM of gssoc, could you add me into the repo. we have mailed regarding this.

**Comment by Trisha-tech** [comment]
> @Trisha-tech im PM of gssoc, could you add me into the repo. we have mailed regarding this.

Hello @sanjay-kv , Can you please tell the procedure of adding into the repo?

**Pull request merged**
