### PR TITLE
Integration of Chatbot  (#306)

### LINKED ISSUE #306: [Feature Request]: Integration of Chatbot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We propose integrating a chatbot that suggests books and provides information about authors to enhance user engagement and boost sales on the website. The chatbot will offer personalized book recommendations based on the customer’s preferences and share author details such as their biography, other works, and interesting facts. This will help customers discover new books and authors while making the shopping experience more interactive and enjoyable.

While I don’t know how to create a chatbot from scratch, I can use a tool I’ve been working with to build a functional one.

### Use Case

Scenario:
A customer visits the website and sees an option to interact with the chatbot. The customer engages with the chatbot by asking for book suggestions or information about specific genres and authors. The chatbot responds based on the customer’s input, providing a curated list of recommended books and sharing relevant author details. The customer can continue asking the bot for more suggestions, learning about different authors, or exploring new books, all based on their preferences.

Outcome:
The chatbot enhances the shopping experience by allowing customers to actively engage with it, providing personalized book recommendations and author insights upon request. This increases customer satisfaction and the likelihood of making a purchase.

### Benefits

1.) Increased Sales: Personalized book suggestions encourage purchases.
2.) Improved User Engagement: Interactive chatbot keeps users engaged longer.
3.) Enhanced Product Discovery: Helps customers find books and authors easily.
4.) Time Efficiency: Quick recommendations save users time.
5.) 24/7 Assistance: Always available to guide customers.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ghost**
### Description
 integrated a chatbot that suggests books and provides information about authors to enhance user engagement and boost sales on the website. The chatbot will offer personalized book recommendations based on the customer’s preferences and share author details such as their biography, other works, and interesting facts. This will help customers discover new books and authors while making the shopping experience more interactive and enjoyable.
A clear and concise description of what the PR does.

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #306 "

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@Trisha-tech hey Trisha tried to reaching you out but I didnt got nay respond added my bot it is working perfectly made it from botpress tho I wnted to check by live server tho it is not opening and asking for Mongo URL  which m not familiar with.

Would be great if you can check and tell me if somethign is need although it is wroking u can merge and check it by yourself too. Thankyou for assigning it to me!!

**Review by Suman373 — COMMENTED** [review]
@Trisha-tech locally index.html shows the third party chatbot via botpress.
image

@snehhhcodes have you customized the chat-bot anyhow to respond to certain type of questions from the user ?

**Comment by snehhhcodes** [comment]
> @Trisha-tech locally index.html shows the third party chatbot via botpress. image
> 
> @snehhhcodes have you customized the chat-bot anyhow to respond to certain type of questions from the user ?

yes i have customized it so that user can easily engage with the bot even if they have more queries and if not thn they can simply choose no and bot will end the chat with a greeting

**Comment by Suman373** [comment]
> > @Trisha-tech locally index.html shows the third party chatbot via botpress. image
> > @snehhhcodes have you customized the chat-bot anyhow to respond to certain type of questions from the user ?
> 
> yes i have customized it so that user can easily engage with the bot even if they have more queries and if not thn they can simply choose no and bot will end the chat with a greeting

Nice work !

**Comment by snehhhcodes** [comment]
@Suman373 Hey suman any update or merging this PR?

**Comment by Suman373** [comment]
> @Suman373 Hey suman any update or merging this PR?

The PA will merge it when she gets time.

**Comment by snehhhcodes** [comment]
> > @Suman373 Hey suman any update or merging this PR?
> 
> The PA will merge it when she gets time.

that means @Trisha-tech ?

**Comment by snehhhcodes** [comment]
> > > @Suman373 Hey suman any update or merging this PR?
> > 
> > 
> > The PA will merge it when she gets time.
> 
> that means @Trisha-tech ?

would be great if you can add hacktoberfest label too

**Comment by Suman373** [comment]
> > > @Suman373 Hey suman any update or merging this PR?
> > 
> > 
> > The PA will merge it when she gets time.
> 
> that means @Trisha-tech ?

Yes

**Pull request merged**
