### PR TITLE
Added home in navbar redirecting to home

### LINKED ISSUE #201: [Feature Request]: Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Use Case

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Benefits

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by arunimaChintu**
### Description
Closes #201
- This PR does the following:
  - Adds ...
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by arunimaChintu** [comment]
@Trisha-tech Please merge this when u are free

**Comment by arunimaChintu** [comment]
@Trisha-tech Also merge this Please... Tomorrow is the final date for gssoc24... Please

**Comment by Trisha-tech** [comment]
> @Trisha-tech Also merge this Please... Tomorrow is the final date for gssoc24... Please

Resolve these conflicts @arunimaChintu 
Added home in navbar redirecting to home by arunimaChintu · Pull Request #205 · Trisha-tech_OnlineBookSales - Google Chrome 7_30_2024 9_58_27 PM

**Comment by arunimaChintu** [comment]
@Trisha-tech Resolved... Please merge this now

**Pull request merged**
