### PR TITLE
faqs section: changed the color of  the answers

### PR DESCRIPTION
**Pull request by ssejal1508**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Fixes the color of the answers in the faq section

### Related Issues
fixes issue #637 

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by shaurya35** [comment]
@shar2710 package-lock.json shouldn't be affected from it, please revert the changes made to it

**Comment by shaurya35** [comment]
@shar2710 can you provide ss of the changes made?

**Comment by shaurya35** [comment]
@shar2710 of the UI not the code

**Comment by shar2710** [comment]
actually i'm getting this problem when i run "npm start"
{58B330BF-824C-412F-B545-ADFF0AB06F88}

**Comment by shaurya35** [comment]
cd client
npm start 

this would do

**Comment by shaurya35** [comment]
@shar2710 also fetch the latest commit if needed

**Comment by shar2710** [comment]
@shaurya35 i've tried doing so multiple times, still it doesn't work

**Pull request closed without merging**
