### PR TITLE
Enhanced Functionality and Styling of Cart Page

### LINKED ISSUE #547: [Feature Request]: Functionality of Cart Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The cart page shows the message in that that 'fail to load cart data' but it should not show that message if your cart is empty
Hence the I will fix this issue and will if the card is empty it will only display the message of cart is empty and there will be no table in that case. Also the way suggested products are listed is not good so I will make the UI of the cart page better as well to make it attractive and appealing

### Use Case

Improved user experience

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhum-ika**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  -Functionality added to display error on loading , Empty cart, and selected items conditionally
  -Styled them accordingly and separately

Fixes #547 

### Screenshots (if applicable)
Screenshot 2024-10-22 130743
Screenshot 2024-10-22 132416

https://github.com/user-attachments/assets/5870fff8-3b3c-4325-9d3f-9552bb5b2200

**This is the dummy content I created to test my changes, it still has increase n decrease functionality in quantity**

### Additional Context
Kindly add all the tags while merging PR.
Thank you for assigning me this issue. 
**If you liked my contribution, kindly upgrade my level because I Not only enhanced UI but worked on functionality too.**

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@Bhum-ika nice work 👍 ! Are you sure your changes don't generate any new warnings ? ( you haven't filled the checkbox in the PR template)

**Comment by Bhum-ika** [comment]
@Trisha-tech 
It will not generate new warnings, I have checked the tickbox now. 
Could you please add level 3 here. I worked hard on this. 
I would really appreciate it

**Comment by Bhum-ika** [comment]
@Trisha-tech Kindly reply

**Comment by Suman373** [comment]
> @Trisha-tech Kindly reply

Hey @Bhum-ika ! The PA might be busy and she will merge them once she gets time. Till then I'd suggest you to look into other issues.

**Pull request merged**
