### PR TITLE
Enhanced the Faq section

### PR DESCRIPTION
**Pull request by Jazz-45**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds Contrasting colors to answer of the faq question in the FAQ Page.

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@Jazz-45 Please mention the issue you have worked on

**Comment by Jazz-45** [comment]
Issue no #286

**Comment by Suman373** [comment]
> Issue no #286
LGTM ! Well done ! 👍

**Comment by Jazz-45** [comment]
> > Issue no #286
> 
> You may add some screenshots for the changes you have made to the FAQ section. Otherwise LGTM ! Well done ! 👍
Thank you sir for appreciation. This really motivates to contribute more.

Screenshot 2024-10-05 231156

**Comment by Suman373** [comment]
> Thank you sir for appreciation. This really motivates to contribute more. Screenshot 2024-10-05 231156

Happy contributing ! ☺

**Review by Trisha-tech — APPROVED** [review]
Nice Work @Jazz-45

**Pull request merged**
