### PR TITLE
Design a Register Page UI #2 & Login page #3

### PR DESCRIPTION
**Pull request by sadvika05**
added login and register.html file

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> added login and register.html file

Hello @sadvika05 , This is a mern stack project. Have you worked on any mern stack project previously?

**Comment by sadvika05** [comment]
@Trisha-tech yes i have worked on MERN stack projects before 
I have made a MERN-stack E-commerce website for my college project
and few other like youtube clone

**Comment by sadvika05** [comment]
@Trisha-tech 
As you did not mention to make these register and login UI using react or in ejs format
i have just made them in basic HTML

**Comment by Trisha-tech** [comment]
> @Trisha-tech As you did not mention to make these register and login UI using react or in ejs format i have just made them in basic HTML

Okay, no problem
Just do one thing, add these files like you make components in react js. 
If you face any difficulty, ping me.

**Comment by sadvika05** [comment]
okay I'll make react components individually
and I have a doubt does this project come under GSSoC'24 because I don't see any labels

**Comment by Trisha-tech** [comment]
> okay I'll make react components individually and I have a doubt does this project come under GSSoC'24 because I don't see any labels

Yes, this project comes under GSSOC'24. Now labels will reflect.

**Comment by sadvika05** [comment]
@Trisha-tech
is this issue got closed?
because I can see login and signup pages are already present right now
did they get added or
now i made it should i make a pull request my committing??

**Pull request closed without merging**
