### PR TITLE
Added AI-BookRecommdation component

### LINKED ISSUE #343: Propose AI-based Book Recommendation System backend to Enhance User Interaction
I would like to propose an enhancement to integrate an AI-based book recommendation system on the platform. The goal of this feature is to analyze users' reading habits and preferences, and then provide personalized book recommendations based on factors such as genres, authors, and user history.
This enhancement will improve user interaction by delivering more relevant book suggestions and helping users discover new books they are likely to enjoy. The AI backend will leverage machine learning algorithms to continuously refine recommendations over time based on user feedback and behavior.

Key Features:
- Personalized book suggestions
- Data-driven recommendations based on user history and preferences
- AI algorithms to refine suggestions and improve user experience
- Integration with existing book catalog

### PR DESCRIPTION
**Pull request by ArpitaAgrahari**
### Description
A clear and concise description of what the PR does:
- This PR introduces AI-based book recommendations by adding sample book titles to the `config.toml` file.
- Enhances the AI recommendation system by fetching book synopses from Goodreads, improving user interaction and providing engaging book suggestions.
- Refactors the configuration setup to accommodate book metadata for seamless integration with the backend.

### Related Issues
- Fixes #343 `Pull_Request`.

### Changes
List the detailed changes made in this PR:
- Added sample book titles and authors to the `config.toml` file, including:
  - **Project Hail Mary** by Andy Weir
  - **Home Before Dark** by Riley Sager
  - **The Invisible Life of Addie LaRue** by V.E. Schwab
- Refactored backend logic to fetch book synopses from Goodreads based on the book titles provided in `config.toml`.
- Updated the book recommendation feature to show a list of books with synopses fetched from external sources.

### Testing Instructions
Follow the steps to test the new changes:
1. Pull this branch.
2. Ensure Python 3 and the required dependencies are installed by running `pip install -r requirements.txt`.
3. Run the main script using `python3 main.py` to fetch the book synopses and generate recommendations.
4. Verify that the system successfully fetches book synopses from Goodreads and displays them correctly in the output.
5. Confirm that book recommendations appear based on user preferences, using the provided book titles and fetched data.

### Screenshots
image

### Additional Context
This PR is based on the proposal to improve user engagement by offering personalized AI-driven book recommendations. The addition of sample book data and integration with Goodreads helps in testing and refining the algorithm.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done:
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I am working on this issue under GSSOC and Hacktoberfest.

### CODE REVIEW

**Comment by ArpitaAgrahari** [comment]
I would like to know is there any issue with the PR or when you will merge the PR ?  It's been a week since I proposed the request to merge.

**Comment by Suman373** [comment]
> I would like to know is there any issue with the PR or when you will merge the PR ? It's been a week since I proposed the request to merge and add label under hacktoberfest, hacktoberfest-accepted, gssoc-24' extd. .

First of all nice work ! Few things I would like to mention : 
1. Our tech stack was/is clearly mentioned. You have instructed a lot of python configuration and setup which makes your contribution more suitable for Python projects.
2. Your PR has 42 commits. It is not a best practice since the reviewers and maintainers will not get the clarity and it makes it difficult to go through it manually.
3. Your screenshot shows some texts but it is not clear if the recommendation is shown in the page where user can see it or we have to run the main.py to get it.

**Review by Suman373 — COMMENTED** [review]
Due to the lack of expertise in python and the domain related to this PR i am not able to add review @Trisha-tech

**Comment by Suman373** [comment]
> > I would like to know is there any issue with the PR or when you will merge the PR ? It's been a week since I proposed the request to merge and add label under hacktoberfest, hacktoberfest-accepted, gssoc-24' extd. .
> 
> First of all nice work ! Few things I would like to mention :
> 
>     1. Our tech stack was/is clearly mentioned. You have instructed a lot of python configuration and setup which makes your contribution more suitable for Python projects.
> 
>     2. Your PR has 42 commits. It is not a best practice since the reviewers and maintainers will not get the clarity and it makes it difficult to review.
> 
>     3. Your screenshot shows some texts but it is not clear if the recommendation is shown in the page where user can see it or we have to run the main.py to get it.

**Pull request merged**
