### PR TITLE
Fetch trending books from booksapi

### LINKED ISSUE #353: [Feature Request]: Fetch trending books from the books api
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Right now the trending and new arrivals shows : 
image

We can update it to add real books using some api.

### Use Case

Account for better UI UX and usability of the product

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aasiflm10**
### Description
Fetches latest trending Newyork times best sellers from the NY_TIMES_BOOK_API.

### Related Issues

- Placeholder: "Fixes #353 "

### Changes
List the detailed changes made in this PR.
- Added improvents to trending section.
- Added a index.js file client/src/Components ( because it was not available before and the project was giving error) 
  So index.js in Components fixed those errors.
- Added a .env file (.env.sample) in client directory ( To access REACT_APP_NY_TIMES_API_KEY in Trending.jsx)

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Create a .env file in client directory. (see .env.sample )
3. Get the NY_TIMES_API_KEY from https://developer.nytimes.com/ ( Create and accont and get the books apikey)
4. Add this apiKey to your .env file.
5. npm install  ( in client)
6. npm start   (in client )

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Screenshots (if applicable)
Screenshot from 2024-10-09 00-22-27

### Additional Context
See issue #353  for more info

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> ### Description
> Fetches latest trending Newyork times best sellers from the NY_TIMES_BOOK_API.
> 
> ### Related Issues
> * Placeholder: "Fixes [[Feature Request]: Fetch trending books from the books api #353](https://github.com/Trisha-tech/OnlineBookSales/issues/353) "
> 
> ### Changes
> List the detailed changes made in this PR.
> 
> * Added improvents to trending section.
> * Added a index.js file client/src/Components ( because it was not available before and the project was giving error)
>   So index.js in Components fixed those errors.
> * Added a .env file (.env.sample) in client directory ( To access REACT_APP_NY_TIMES_API_KEY in Trending.jsx)
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Create a .env file in client directory. (see .env.sample )
> 3. Get the NY_TIMES_API_KEY from https://developer.nytimes.com/ ( Create and accont and get the books apikey)
> 4. Add this apiKey to your .env file.
> 5. npm install  ( in client)
> 6. npm start   (in client )
> 
> ### Screenshots (if applicable)
> Add any screenshots that help explain or visualize the changes.
> 
> ### Screenshots (if applicable)
> Screenshot from 2024-10-09 00-22-27
> 
> ### Additional Context
> See issue #353 for more info
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly resolve these conflicts @aasiflm10 
Bug _ Fix the Register and Signup Issues by amitroy-thedev · Pull Request #390 · Trisha-tech_OnlineBookSales - Google Chrome 10_9_2024 6_52_55 PM

**Comment by aasiflm10** [comment]
Merge conflicts solved. @Trisha-tech

**Comment by Trisha-tech** [comment]
> Merge conflicts solved. @Trisha-tech

Still showing conflict in Home.jsx @aasiflm10 
Fetch trending books from booksapi by aasiflm10 · Pull Request #395 · Trisha-tech_OnlineBookSales - Google Chrome 10_10_2024 11_18_01 PM

**Comment by aasiflm10** [comment]
image

Please check i have solved all merge conflicts. @Trisha-tech

**Pull request merged**
