### PR TITLE
Added the backend part for Google Sign IN

### LINKED ISSUE #274: [Feature Request]: Integrate Google Sign-In for User Authentication
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Overview: The addition of Google Sign-In would streamline user authentication by allowing users to sign in to the OnlineBookSales platform with their Google accounts. This feature will simplify the login process, improve security through OAuth 2.0, and reduce the friction of manual account creation.

Proposed Implementation:

Frontend: Add a "Sign in with Google" button on the login and sign-up pages. Upon clicking the button, the user will be prompted to authenticate using their Google account.

Backend: Once authenticated, the backend should verify the received ID token using Google’s OAuth 2.0 API. A new user account will be created for first-time logins, and existing users will be logged in automatically if their Google account is linked to their profile.

Expected Outcome:

Users will be able to sign in without needing to manually input their email and password, improving ease of access.
Security will be enhanced since OAuth 2.0 is a more secure authentication method.

### Use Case

As a user of the Online Book Sales web application,
I want to be able to sign in using my Google account,
so that I can quickly and securely log in without the need to create a new account or remember a new set of credentials.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by pushkardev123**
This PR does the following:
Adds Google authentication functionality to the application.
Updates the server configuration to handle OAuth authentication.
Fixes potential CORS issues to allow frontend requests.

Related Issues
Fixes #274 

Changes
Implemented Google OAuth 2.0 authentication using the passport-google-oauth20 strategy.
Configured environment variables to securely store Google Client ID and Client Secret.
Added a new endpoint for handling Google authentication callbacks.

Testing Instructions
Detailed instructions on how to test the changes:

Pull this branch.
Run npm install to install dependencies.
Ensure that your .env file includes valid GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET.
Start the server using npm start.
Navigate to http://localhost:5000/auth/google to initiate Google authentication.
Verify that users can log in using their Google accounts and that the user profile is correctly handled in the application.

Additional Context
Any additional context or information that reviewers should be aware of:

This PR is based on the integration of Google authentication to improve user experience and streamline the login process.
This is the backend part, the google sign in button still need to be designed at the frontend and redirected properly.
I request the publisher to please generate Google OAuth client id and secret to proceed with the linkage in the website.

Checklist
 [x] I have performed a self-review of my code
 [x] I have commented on my code, particularly in hard-to-understand areas
 [x] My changes generate no new warnings
 [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by pushkardev123** [comment]
@Trisha-tech can you please review my code and merge my PR request?

**Review by Suman373 — COMMENTED** [review]
Well done @pushkardev123 ! Right now your backend does not seem to handle the check if user exists in the database and create account if they don't. Will you be able to address this issue ?

**Comment by pushkardev123** [comment]
Ya sure, will look after that.

**Comment by Suman373** [comment]
> Ya sure, will look after that.

Okay. Good luck then!

**Comment by pushkardev123** [comment]
i cant see any user schema defined in the models ?, may i know why is that. I am creating a sample user model for mongodb in this pr request lemme know if there's something else i should be knowing

**Comment by Suman373** [comment]
> i cant see any user schema defined in the models ?, may i know why is that. I am creating a sample user model for mongodb in this pr request lemme know if there's something else i should be knowing

@pushkardev123  There is a customer schema for the customer(user).

**Comment by pushkardev123** [comment]
can you specify the directory please?

**Comment by Suman373** [comment]
> can you specify the directory please?

models/customerSchema.js

**Comment by pushkardev123** [comment]
okay thanks

**Comment by pushkardev123** [comment]
so here ive updated the customer schema given by you and as you've told to check the db for existing user or not, and if not create one, ive modified the customerSchema a bit by adding a googleID field with sparse : true as for to check if it is log inned by google id, but it's optional and anyone can login with google id or email!

Hope this explanation explains it all, do let me know if i can do something further.

**Review by Suman373 — APPROVED** [review]
LGTM

**Comment by Trisha-tech** [comment]
> This PR does the following: Adds Google authentication functionality to the application. Updates the server configuration to handle OAuth authentication. Fixes potential CORS issues to allow frontend requests.
> 
> Related Issues Fixes #274
> 
> Changes Implemented Google OAuth 2.0 authentication using the passport-google-oauth20 strategy. Configured environment variables to securely store Google Client ID and Client Secret. Added a new endpoint for handling Google authentication callbacks.
> 
> Testing Instructions Detailed instructions on how to test the changes:
> 
> Pull this branch. Run npm install to install dependencies. Ensure that your .env file includes valid GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET. Start the server using npm start. Navigate to http://localhost:5000/auth/google to initiate Google authentication. Verify that users can log in using their Google accounts and that the user profile is correctly handled in the application.
> 
> Additional Context Any additional context or information that reviewers should be aware of:
> 
> This PR is based on the integration of Google authentication to improve user experience and streamline the login process. This is the backend part, the google sign in button still need to be designed at the frontend and redirected properly. I request the publisher to please generate Google OAuth client id and secret to proceed with the linkage in the website.
> 
> Checklist [x] I have performed a self-review of my code [x] I have commented on my code, particularly in hard-to-understand areas [x] My changes generate no new warnings [x] I am working on this issue under GSSOC

Well Done @pushkardev123

**Comment by pushkardev123** [comment]
😄Thank you very much for letting me contribute to this project, it was great interacting with you guys.

**Comment by Suman373** [comment]
> 😄Thank you very much for letting me contribute to this project, it was great interacting with you guys.

Likewise ! Happy contributing !

**Pull request merged**
