### PR TITLE
Dark Theme of Website Updated Issue no #290 Resolved

### LINKED ISSUE #290: Enhance the Dark Theme of the Website
I want to Enhance the Dark theme of the website it not up to mark experience is not so good in dark mode.

@Trisha-tech Please assign this issue to me.

### PR DESCRIPTION
**Pull request by rajatsinghal02**
Fixes #290 

Screenshot 2024-10-06 134458

I have Enhance the Dark theme of the website
@Trisha-tech  Please Merge this pull request with the labels attached.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
> Fixes #290
> 
> Screenshot 2024-10-06 134458
> 
> I have Enhance the Dark theme of the website @Trisha-tech Please Merge this pull request with the labels attached.
> ### Checklist
> 
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
>     * [ x] I have performed a self-review of my code
> 
>     * [ x] I have commented my code, particularly in hard-to-understand areas
> 
>     * [x ] My changes generate no new warnings
> 
>     * [x ] I am working on this issue under GSSOC

Nice work ! Could you please send the before vs after screenshots for better clarity.

**Review by Trisha-tech — APPROVED** [review]
Good work @rajatsinghal02

**Comment by Suman373** [comment]
> Before Screenshot 2024-10-06 141928
> 
> After
> 
> Screenshot 2024-10-06 134458
> 
> @Suman373 Please merge the PR with labels attached

Thanks ! Well done 👍

**Comment by puneeth072003** [comment]
@Trisha-tech @Suman373 @rajatsinghal02 

Screenshot 2024-10-16 072923
I think dark mode logo would look better if in png format, the above one looks odd

**Comment by Suman373** [comment]
> @Trisha-tech @Suman373 @rajatsinghal02
> 
> Screenshot 2024-10-16 072923 I think dark mode logo would look better if in png format, the above one looks odd

Yes, if you want to work on this small fix u may create an issue regarding this.

**Pull request merged**
