### PR TITLE
  Fixed Search Function to Notify Users of Empty Input and No Matching Books

### LINKED ISSUE #423: [Bug]: Search Filter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have typed the name of a book into the search bar and no matching book is found, there is no feedback or result shown. This creates confusion for the user, as they don't know if the search is still processing, if there was an error, or if the book simply doesn't exist in the database.

### Expected behavior

Display a pop-up card or message notifying the user that the book was not found.

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by darshinihoney**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  Fixes the issue where no message was shown when a book search returned no results.
  Updates the search feature to display a notification when no book is found in the database.

### Related Issues
- "Fixes #423 "

### Changes
List the detailed changes made in this PR.
Added a pop-up message when the search returns no matching books.
Refactored the search component to handle empty result sets more efficiently.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Search for a non-existent book, and verify that a pop-up card or message is displayed, notifying the user that no results were found.

### Screenshots (if applicable)
https://github.com/user-attachments/assets/c80ca259-dbde-4dce-8d12-d19305314b42

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on user feedback regarding the confusion when book search results are empty.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by darshinihoney** [comment]
@Trisha-tech  I wanted to let you know that the search filter bug has been solved. Please take some time to check it out, and let me know if there are any changes or improvements you would like to suggest.

**Comment by Trisha-tech** [comment]
> ### Description
> A clear and concise description of what the PR does.
> 
> * This PR does the following:
>   Fixes the issue where no message was shown when a book search returned no results.
>   Updates the search feature to display a notification when no book is found in the database.
> 
> ### Related Issues
> * "Fixes [[Bug]: Search Filter #423](https://github.com/Trisha-tech/OnlineBookSales/issues/423) "
> 
> ### Changes
> List the detailed changes made in this PR. Added a pop-up message when the search returns no matching books. Refactored the search component to handle empty result sets more efficiently.
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Run `npm install` to install dependencies.
> 3. Run `npm test` to execute the test suite.
> 4. Search for a non-existent book, and verify that a pop-up card or message is displayed, notifying the user that no results were found.
> 
> ### Screenshots (if applicable)
>  searchbug.1.mp4 
> ### Additional Context
> Any additional context or information that reviewers should be aware of.
> 
> * This PR is based on user feedback regarding the confusion when book search results are empty.
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly resolve these conflicts @darshinihoney 
Fixed Search Function to Notify Users of Empty Input and No Matching Books by darshinihoney · Pull Request #476 · Trisha-tech_OnlineBookSales - Google Chrome 10_22_2024 2_24_01 PM

**Comment by darshinihoney** [comment]
@Trisha-tech I have resolved the commit conflicts and checked them to ensure everything is in sync. Let me know if further review is needed.

**Comment by Trisha-tech** [comment]
> @Trisha-tech I have resolved the commit conflicts and checked them to ensure everything is in sync. Let me know if further review is needed.

Kindly look into your code which changes the features that have already been implemented. Pull the merge commit before your code, add your changes and then make the pull request again. @darshinihoney

**Pull request merged**
