### PR TITLE
Enhances With Best Code Practices, Code Style Guidelines And Acknowledgments

### LINKED ISSUE #501: [Documentation Update]: Added These Things Best Practices, Code Style Guidelines, and Acknowledgments
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

It was a straightforward approach before

### Suggested Change

I have enhanced it to make it more clearly understandable by the user or contributor.

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by milansamuel609**
### Description
Enhances the full documentation with best code practices, code style guidelines and acknowledgments

### Related Issues
Link any related issues using the format `Fixes #501 `. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #501 "

### Changes
List the detailed changes made in this PR.
- Added Best Code Practices
- Added Code Style Guidelines
- Added Acknowledgments

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
image

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by milansamuel609** [comment]
@Trisha-tech I have again re-requested the PR. Please kindly check once again. I have also raised issue for this. If you get any issue please message me. If its fine then please merge it and attach the gssoc extend label.

**Comment by Suman373** [comment]
Good work !

**Comment by milansamuel609** [comment]
> Good work !

Thank you 🙂

**Comment by milansamuel609** [comment]
@Trisha-tech could you please let me know how long it might take for the review to be completed ? I appreciate your assistance and look forward to your response.

**Pull request merged**
