### PR TITLE
Revert "added searchProduct and filterProduct controllers in product …

### PR DESCRIPTION
**Pull request by ArtiGaund**
…controllers"

This reverts commit ff197d7e1139e85ebf524c11f48b2e8f581a71fc.

Can you can is it correct. 

issue #10

### CODE REVIEW

**Comment by Trisha-tech** [comment]
@ArtiGaund Resolve all these conflicts
screenshot-github com-2024 05 12-12_52_03

**Comment by ArtiGaund** [comment]
ok

**Comment by ArtiGaund** [comment]
Can you check now? where search and filter controllers are visible or not?

**Comment by sanjay-kv** [comment]
Hi @Trisha-tech 
This is sanjay, PM gssoc
I would like to know why its not yet merged , let me know if any technical issue I can help you with .

**Comment by ArtiGaund** [comment]
@sanjay-kv it was level2 issue #10

**Comment by sanjay-kv** [comment]
your issue is still open admin has to merge it to appear on leaderboard.

**Comment by ArtiGaund** [comment]
ok

**Pull request merged**
