### PR TITLE
Shop page frontend+backend

### PR DESCRIPTION
**Pull request by Sneha0019**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ... 
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...  
-  in shop page which I design, the changes are dynamic when you will add your mongo url then you can create product which you will add to mongodb and then directly it will be shown to your website
- Also It filters each category wise records as shown in pictures 

- Refactored the ... frontent + Backend (Updates in backend in index.js for routes in products and changes in frontend page shops also added a productitem page where all the products will be loaded from backend)
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I am working on this issue under GSSOC

Category Wise division 
Screenshot 2024-06-13 123616

Screenshot 2024-06-13 123625

Database photo
image

### CODE REVIEW

**Comment by Sneha0019** [comment]
@Trisha-tech please review the PR!

**Comment by Trisha-tech** [comment]
> @Trisha-tech please review the PR!

Resolve these conflicts
screenshot-github com-2024 06 15-13_32_38

**Comment by Sneha0019** [comment]
Hello, @Trisha-tech I've solved 2/3 conflicts and one conflict which I am facing in index.js that seems to be related to spacing or formatting, and I'm having trouble understanding its exact nature.
Could you please assist me in understanding the conflict and how to resolve it? Your guidance on this matter would be greatly appreciated.
Looking forward for your response. Thank you!

**Comment by Trisha-tech** [comment]
> Hello, @Trisha-tech I've solved 2/3 conflicts and one conflict which I am facing in index.js that seems to be related to spacing or formatting, and I'm having trouble understanding its exact nature. Could you please assist me in understanding the conflict and how to resolve it? Your guidance on this matter would be greatly appreciated. Looking forward for your response. Thank you!

Remove double addition of lines such as 'mongoose' 
screenshot-github com-2024 06 15-17_33_24


One more thing, we are creating website for online books purchase. Replace these images like romance and secrets of life with the much more technical content, biographies, etc.

**Comment by Sneha0019** [comment]
So, the conflict is in the below part, otherwise all is correct as I compared code with original code but its not resolving also I tried to format/ remove the line. Can you further assist me in this? 
image


Also about the categories like romance and science etc. It depends on what data you are adding and in productSchema there is one field name categories so whatever you add in that category it will sort and create sections on that basis. The screenshot I attached is based on the data I added in my Database. But if you will add biographies or educational books then you have to add in category the same name which will be then sort and will create different sections on categories which is in database. I edited the photo and now that category will not be shown. Sorry for the incovenience!

**Comment by Sneha0019** [comment]
Hey, @Trisha-tech I tried my best to resolve error is below but from my side I have pushed correctly in my last commit name "final commit"
conflicting code
image

 Visual Studio code 
image

Can you please assist me further? 

Also about the categories like romance and science etc. It depends on what data you are adding and in productSchema there is one field name categories so whatever you add in that category it will sort and create sections on that basis. The screenshot I attached is based on the data I added in my Database. But if you will add biographies or educational books then you have to add in category the same name which will be then sort and will create different sections on categories which is in database. I edited the photo and now that category will not be shown. Sorry for the incovenience!

**Pull request merged**
