### PR TITLE
Readme file Issue Updation

### PR DESCRIPTION
**Pull request by itsbhh**
**### Updated README Structure:**

Added Navigation: A new navigation section was included at the top of the README to enhance user experience. This allows users to quickly navigate to important sections such as Tech Stack, How to Fork, How to Contribute, Code of Conduct, and Contact Information.
Revised Contribution Guide: Clearer instructions were added for contributing to the project, including step-by-step details on how to fork the repository, create new branches, make changes, and submit a pull request.
Included Code of Conduct: A section for the project's Code of Conduct was added, ensuring contributors are aware of community guidelines and acceptable behavior.
Contact Information: A contact section was introduced for any inquiries or support, directing users where they can reach out for help.
Other Visual Enhancements: The layout and formatting were improved for better readability and aesthetics, including the addition of icons, badges, and emojis to make the README visually appealing.

**### Please label this under GSSOC'24 extd and Hacktoberfest-accepted and pls add the label of the level I did contribute.**

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> **### Updated README Structure:**
> 
> Added Navigation: A new navigation section was included at the top of the README to enhance user experience. This allows users to quickly navigate to important sections such as Tech Stack, How to Fork, How to Contribute, Code of Conduct, and Contact Information. Revised Contribution Guide: Clearer instructions were added for contributing to the project, including step-by-step details on how to fork the repository, create new branches, make changes, and submit a pull request. Included Code of Conduct: A section for the project's Code of Conduct was added, ensuring contributors are aware of community guidelines and acceptable behavior. Contact Information: A contact section was introduced for any inquiries or support, directing users where they can reach out for help. Other Visual Enhancements: The layout and formatting were improved for better readability and aesthetics, including the addition of icons, badges, and emojis to make the README visually appealing.
> 
> **### Please label this under GSSOC'24 extd and Hacktoberfest-accepted and pls add the label of the level I did contribute.**

Kindly add the issue no you are addressing @itsbhh

**Comment by itsbhh** [comment]
> > **### Updated README Structure:**
> > Added Navigation: A new navigation section was included at the top of the README to enhance user experience. This allows users to quickly navigate to important sections such as Tech Stack, How to Fork, How to Contribute, Code of Conduct, and Contact Information. Revised Contribution Guide: Clearer instructions were added for contributing to the project, including step-by-step details on how to fork the repository, create new branches, make changes, and submit a pull request. Included Code of Conduct: A section for the project's Code of Conduct was added, ensuring contributors are aware of community guidelines and acceptable behavior. Contact Information: A contact section was introduced for any inquiries or support, directing users where they can reach out for help. Other Visual Enhancements: The layout and formatting were improved for better readability and aesthetics, including the addition of icons, badges, and emojis to make the README visually appealing.
> > **### Please label this under GSSOC'24 extd and Hacktoberfest-accepted and pls add the label of the level I did contribute.**
> 
> Kindly add the issue no you are addressing @itsbhh

#279

**Comment by Suman373** [comment]
@itsbhh I think the emojis/icons looked better. There was no need to remove them completely. Also provide some screenshots of how your documentation changes finally look.

**Comment by itsbhh** [comment]
> @itsbhh I think the emojis/icons looked better. There was no need to remove them completely. Also provide some screenshots of how your documentation changes finally look.

To keep the readme simple and not to overwhelm things..

** I Added Code of conduct, contact information and also there were some numbering issue in your content table fixed that and added table of contents **

Screenshot_20241004_170022_Samsung Internet

Screenshot_20241004_170050_Samsung Internet
Screenshot_20241004_170104_Samsung Internet

**Review by Suman373 — APPROVED** [review]
LGTM !

**Pull request merged**
