### PR TITLE
Update cors origin configuration #473

### LINKED ISSUE #473: [Bug]: CORS Policy Error During Customer Registration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The CORS policy blocks the request when trying to register a new customer. The error message is: No 'Access-Control-Allow-Origin' header is present on the requested resource, causing the request to fail with the status ERR_FAILED.

### Expected behavior

The customer registration request should successfully pass the preflight check and complete the registration without being blocked by the CORS policy.

### Add ScreenShots

i faced this problem, please assign me
Screenshot 2024-10-14 173902

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by skanarul8002**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds correct CORS configuration to allow requests from the deployed frontend at `https://book4u-j5au.onrender.com` and also allow for all requests.
  - Fixes the CORS error that blocked frontend-backend communication.
  - Updates the backend server's CORS policy to support credentials and necessary HTTP methods.

### Related Issues
- Fixes #473

### Changes
List the detailed changes made in this PR.
- Updated `cors` middleware to allow origins.
- Allowed `GET`, `POST`, `PUT`, `DELETE`, and `OPTIONS` methods for the frontend.
- Ensured that cookies and credentials can be passed from the frontend to the backend.

### Screenshots (if applicable)
image

### Additional Context
- This PR is based on resolving the CORS error during frontend-backend communication for the registration page.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by skanarul8002** [comment]
Hi @Trisha-tech , can you please add the "hacktoberfest-accepted" label also to this PR as it is part of Hacktoberfest? Thank you!

**Comment by Suman373** [comment]
@skanarul8002 Allowing all origins is good for dev mode but in production it is not preferred. Instead using an array with localhost and production url is more secure. In this case : 
1. http://localhost:3000
2. https://book4u-j5au.onrender.com/

**Comment by skanarul8002** [comment]
Yes, @Suman373, I agree with you. However, this should only be allowed on the development side because most contributors face this problem, and that's why I allow all origins after cloning; it may work properly on the development side. Okay, I'll add this particular origin.

**Comment by Suman373** [comment]
> Yes, @Suman373, I agree with you. However, this should only be allowed on the development side because most contributors face this problem, and that's why I allow all origins after cloning; it may work properly on the development side. Okay, I'll add this particular origin.

Your changed origin doesn't generate any error and ready for merging right ? @skanarul8002

**Review by Trisha-tech — APPROVED** [review]
Good work

**Pull request merged**
