### PR TITLE
Progressbar implemented

### LINKED ISSUE #511: [Feature Request]: Missing Progress Bar and Hamburger Functionality on Pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

mplement a progress bar at the top of each page to visually indicate the user's scroll position, enhancing navigation and user experience. Additionally, create a responsive hamburger menu that drops down from the top when clicked, allowing easy access to navigation links on mobile devices.

### Use Case

Implementing the progress bar and hamburger menu would significantly improve user experience by:

The hamburger menu provides a clean, organized way to access navigation links, especially on mobile devices, making it easier for users to explore content without clutter.

The progress bar gives users immediate visual feedback on their scrolling position, enhancing engagement and encouraging them to explore more of the page.

Both features contribute to a modern, responsive design, ensuring accessibility and usability across various devices, which can lead to increased user retention and satisfaction.

### Benefits

_No response_

### Add ScreenShots

No progressbar:

Screenshot 2024-10-16 192824

No hamburger:

Screenshot 2024-10-16 192848

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by srishti023**
### Description
This PR implements a responsive progress bar with a bluish-to-yellowish gradient that visually represents the user's scroll progress on the webpage. The gradient adds a modern and dynamic feel to the UI, smoothly transitioning as the user scrolls. The progress bar adapts well to different screen sizes, ensuring a consistent and appealing user experience across devices.

- This PR does the following:
  - Adds Bluish-to-yellowish gradient for a visually striking look.
  - Smooth animation reflecting scrolling progress.
  - Responsive design that adjusts based on screen size.

### Related Issues
Link any related issues using the format `Fixes #511`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #511"

### Changes
List the detailed changes made in this PR.

- Added a new feature to implement a scroll progress bar that tracks the user's scroll activity and displays it as a bluish-to-yellowish gradient.
- Refactored the existing layout CSS to ensure proper responsiveness for the progress bar across all screen sizes (mobile, tablet, desktop).
- Enhanced the scrolling animation for a smoother transition effect when the progress bar updates as the user scrolls.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/user-attachments/assets/2d2dc023-6be5-4733-9de1-b6da8ba45061

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@srishti023  Nice work ! But why does your commit remove the Sidebar component ?

**Comment by Trisha-tech** [comment]
> ### Description
> This PR implements a responsive progress bar with a bluish-to-yellowish gradient that visually represents the user's scroll progress on the webpage. The gradient adds a modern and dynamic feel to the UI, smoothly transitioning as the user scrolls. The progress bar adapts well to different screen sizes, ensuring a consistent and appealing user experience across devices.
> 
> * This PR does the following:
>   
>   * Adds Bluish-to-yellowish gradient for a visually striking look.
>   * Smooth animation reflecting scrolling progress.
>   * Responsive design that adjusts based on screen size.
> 
> ### Related Issues
> Link any related issues using the format `Fixes #511`. This helps to automatically close related issues when the PR is merged.
> 
> * Placeholder: "Fixes [[Feature Request]: Missing Progress Bar and Hamburger Functionality on Pages #511](https://github.com/Trisha-tech/OnlineBookSales/issues/511)"
> 
> ### Changes
> List the detailed changes made in this PR.
> 
> * Added a new feature to implement a scroll progress bar that tracks the user's scroll activity and displays it as a bluish-to-yellowish gradient.
> * Refactored the existing layout CSS to ensure proper responsiveness for the progress bar across all screen sizes (mobile, tablet, desktop).
> * Enhanced the scrolling animation for a smoother transition effect when the progress bar updates as the user scrolls.
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Run `npm install` to install dependencies.
> 3. Run `npm test` to execute the test suite.
> 4. Verify that ...
> 
> ### Screenshots (if applicable)
> Add any screenshots that help explain or visualize the changes.
> 
>  Online.Book.Sales.-.Google.Chrome.2024-10-20.11-14-49.mp4 
> ### Additional Context
> Any additional context or information that reviewers should be aware of.
> 
> * This PR is based on the following...
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly resolve these conflicts @srishti023 
Fixed Search Function to Notify Users of Empty Input and No Matching Books by darshinihoney · Pull Request #476 · Trisha-tech_OnlineBookSales - Google Chrome 10_22_2024 2_31_40 PM

**Comment by srishti023** [comment]
please check

**Comment by srishti023** [comment]
Please merge my PR

**Pull request merged**
