### PR TITLE
.Redesign the signup/login both page with modern style

### LINKED ISSUE #612: [Feature Request]: redesign the register & login page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Redesign the login page its looking so dull 
Screenshot 2024-10-25 at 1 25 48 AM
i
Screenshot 2024-10-25 at 1 25 52 AM
its looking so simple 

### Use Case

enhance the user interface !!
to look modern login page 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by REHAN-18**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
 
  - Updates ...Updates ...Redesign the signup/login both page with modern style

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #612 "

### Changes
List the detailed changes made in this PR.
[redesign the sign up page page /login page as well]

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by shaurya35** [comment]
@REHAN-18 since the changes should me made for signup and login, please remove the changes for Navbar and NewArrivals, I'd suggest you to create a new branch and redo the process just for the signup and login form
if you're getting any doubts, please refer this
https://github.com/Trisha-tech/OnlineBookSales/blob/master/CONTRIBUTING.md

**Comment by shaurya35** [comment]
@REHAN-18 also please use tailwind

**Comment by REHAN-18** [comment]
> @REHAN-18 also please use tailwind

BRO when we run the website there are many bugs that doesnot run so to run I changed the navbar !

**Comment by shaurya35** [comment]
@REHAN-18 I have fixed the code break
image

please make a pull request with the required changes, pull the latest code and just change whats required
I hope you understand

**Comment by shaurya35** [comment]
@REHAN-18 as mentioned your task is to improve UI for signup and login

**Comment by REHAN-18** [comment]
> @REHAN-18 as mentioned your task is to improve UI for signup and login

ok I will fix &b make new pr

**Comment by REHAN-18** [comment]
> @REHAN-18 as mentioned your task is to improve UI for signup and login

Screenshot 2024-10-30 at 7 29 06 PM
see when I run this is appear

**Comment by shaurya35** [comment]
> > @REHAN-18 as mentioned your task is to improve UI for signup and login
> 
> Screenshot 2024-10-30 at 7 29 06 PM
> see when I run this is appear

You will have to redirect to client directory to npm start it

**Comment by REHAN-18** [comment]
> > > @REHAN-18 as mentioned your task is to improve UI for signup and login
> > 
> > 
> > Screenshot 2024-10-30 at 7 29 06 PM
> > see when I run this is appear
> 
> You will have to redirect to client directory to npm start it

yes 

> > > @REHAN-18 as mentioned your task is to improve UI for signup and login
> > 
> > 
> > Screenshot 2024-10-30 at 7 29 06 PM
> > see when I run this is appear
> 
> You will have to redirect to client directory to npm start it

yes I ve done this but how I ve to check the signup/login page how they look so to open

**Comment by REHAN-18** [comment]
> > > @REHAN-18 as mentioned your task is to improve UI for signup and login
> > 
> > 
> > Screenshot 2024-10-30 at 7 29 06 PM
> > see when I run this is appear
> 
> You will have to redirect to client directory to npm start it

yes 

> > > @REHAN-18 as mentioned your task is to improve UI for signup and login
> > 
> > 
> > Screenshot 2024-10-30 at 7 29 06 PM
> > see when I run this is appear
> 
> You will have to redirect to client directory to npm start it

yes I ve done this but how I ve to check the signup/login page how they look so to open

**Comment by shaurya35** [comment]
@REHAN-18 i didn't get you

**Comment by REHAN-18** [comment]
> @REHAN-18 i didn't get you
To check the UI updates of the  website, I follow this process: I navigate to the client directory, run npm install, and then npm start to launch the server. However, when the server starts, I encounter an error message."

**Comment by REHAN-18** [comment]
> @REHAN-18 i didn't get you

@shaurya35 To check the UI updates of the  website, I follow this process: I navigate to the client directory, run npm install, and then npm start to launch the server. However, when the server starts, I encounter an error message."

**Pull request closed without merging**
