### PR TITLE
issue#99 Build fail along with bad coding errors 

### PR DESCRIPTION
**Pull request by amit429**
Unwanted imports and wrongly written routes were causing the build fail. I have fixed the routing in this pull request . Please refer to the issue #99 for the same as it was urgent i have created the issue and also the pull request. @Trisha-tech please review and merge

### CODE REVIEW

**Comment by amit429** [comment]
@Trisha-tech Please have a look into this

**Comment by Trisha-tech** [comment]
> @Trisha-tech Please have a look into this

@amit429 Still showing error. and package-lock.json conflicts
App js - GSSOC'24-Book - Visual Studio Code 5_15_2024 9_14_22 PM

**Comment by amit429** [comment]
@Trisha-tech there is an external npm package @heroicons/react so i had installed the package and pushed the package.json

**Comment by amit429** [comment]
@Trisha-tech i pulled the latest pushed code from the main , its working correctly now

**Pull request merged**
