### PR TITLE
background color changed of the toggle button

### PR DESCRIPTION
**Pull request by sayanp607**
### Description
A clear and concise description of what the PR does.
This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.

### Related Issues
Fixes: #551 

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.
Screenshot 2024-10-22 085603

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Suman373** [comment]
@sayanp607 Good work ! @Trisha-tech You may verify and merge it

**Comment by Trisha-tech** [comment]
> ### Description
> A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> 
> ### Related Issues
> Fixes: #551
> 
> ### Screenshots (if applicable)
> Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Keep the color like other links i.e. white @sayanp607

**Comment by Suman373** [comment]
> > > ### Description
> > > A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> > > ### Related Issues
> > > Fixes: #551
> > > ### Screenshots (if applicable)
> > > Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> > > ### Checklist
> > > Make sure to check off all the items before submitting. Mark with [x] if done.
> > > 
> > > * [x]    I have performed a self-review of my code
> > > * [ ]    I have commented my code, particularly in hard-to-understand areas
> > > * [x]    My changes generate no new warnings
> > > * [x]    I am working on this issue under GSSOC
> > 
> > 
> > Keep the color like other links i.e. white @sayanp607
> 
> kindly, check it now.

Provide a screenshot of the change please.

**Comment by sayanp607** [comment]
> > > > ### Description
> > > > A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> > > > ### Related Issues
> > > > Fixes: #551
> > > > ### Screenshots (if applicable)
> > > > Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> > > > ### Checklist
> > > > Make sure to check off all the items before submitting. Mark with [x] if done.
> > > > 
> > > > * [x]     I have performed a self-review of my code
> > > > * [ ]     I have commented my code, particularly in hard-to-understand areas
> > > > * [x]     My changes generate no new warnings
> > > > * [x]     I am working on this issue under GSSOC
> > > 
> > > 
> > > Keep the color like other links i.e. white @sayanp607
> > 
> > 
> > kindly, check it now.
> 
> Provide a screenshot of the change please.

Screenshot 2024-10-22 230644

**Comment by Suman373** [comment]
LGTM !

**Comment by Trisha-tech** [comment]
> > > > > ### Description
> > > > > A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> > > > > ### Related Issues
> > > > > Fixes: #551
> > > > > ### Screenshots (if applicable)
> > > > > Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> > > > > ### Checklist
> > > > > Make sure to check off all the items before submitting. Mark with [x] if done.
> > > > > 
> > > > > * [x]      I have performed a self-review of my code
> > > > > * [ ]      I have commented my code, particularly in hard-to-understand areas
> > > > > * [x]      My changes generate no new warnings
> > > > > * [x]      I am working on this issue under GSSOC
> > > > 
> > > > 
> > > > Keep the color like other links i.e. white @sayanp607
> > > 
> > > 
> > > kindly, check it now.
> > 
> > 
> > Provide a screenshot of the change please.
> 
> Screenshot 2024-10-22 230644

I want only lines as the toggle button not the circle encircled it. @sayanp607

**Comment by sayanp607** [comment]
> > > > > > ### Description
> > > > > > A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> > > > > > ### Related Issues
> > > > > > Fixes: #551
> > > > > > ### Screenshots (if applicable)
> > > > > > Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> > > > > > ### Checklist
> > > > > > Make sure to check off all the items before submitting. Mark with [x] if done.
> > > > > > 
> > > > > > * [x]       I have performed a self-review of my code
> > > > > > * [ ]       I have commented my code, particularly in hard-to-understand areas
> > > > > > * [x]       My changes generate no new warnings
> > > > > > * [x]       I am working on this issue under GSSOC
> > > > > 
> > > > > 
> > > > > Keep the color like other links i.e. white @sayanp607
> > > > 
> > > > 
> > > > kindly, check it now.
> > > 
> > > 
> > > Provide a screenshot of the change please.
> > 
> > 
> > Screenshot 2024-10-22 230644
> 
> I want only lines as the toggle button not the circle encircled it. @sayanp607

Yes, I made it now like that.
Screenshot 2024-10-23 141337

**Comment by sayanp607** [comment]
> > > > > > > ### Description
> > > > > > > A clear and concise description of what the PR does. This pr fixes the the background color of the toggle button because previously it was transparent according to @tailwind base.
> > > > > > > ### Related Issues
> > > > > > > Fixes: #551
> > > > > > > ### Screenshots (if applicable)
> > > > > > > Add any screenshots that help explain or visualize the changes. Screenshot 2024-10-22 085603
> > > > > > > ### Checklist
> > > > > > > Make sure to check off all the items before submitting. Mark with [x] if done.
> > > > > > > 
> > > > > > > * [x]        I have performed a self-review of my code
> > > > > > > * [ ]        I have commented my code, particularly in hard-to-understand areas
> > > > > > > * [x]        My changes generate no new warnings
> > > > > > > * [x]        I am working on this issue under GSSOC
> > > > > > 
> > > > > > 
> > > > > > Keep the color like other links i.e. white @sayanp607
> > > > > 
> > > > > 
> > > > > kindly, check it now.
> > > > 
> > > > 
> > > > Provide a screenshot of the change please.
> > > 
> > > 
> > > Screenshot 2024-10-22 230644
> > 
> > 
> > I want only lines as the toggle button not the circle encircled it. @sayanp607
> 
> Yes, I made it now like that. Screenshot 2024-10-23 141337

Is it ok now? @Trisha-tech

**Pull request merged**
