### PR TITLE
Resolved Conflicts (to merge Home Page)

### PR DESCRIPTION
**Pull request by Vivek-yadav01**

### CODE REVIEW

**Comment by Vivek-yadav01** [comment]
mam should i go for integration our frontend with backend?

**Comment by Vivek-yadav01** [comment]
add make suitable change in frontend according to backend.....

**Comment by Vivek-yadav01** [comment]
mam i resolve all the conflicts and u can continue with this homepage then we can modify our frontend as per requirements

**Comment by Vivek-yadav01** [comment]
mam will you merge it or I would start working  on other issues?

**Comment by Trisha-tech** [comment]
> mam will you merge it or I would start working on other issues?

Still showing conflicts
Resolved Conflicts (to merge Home Page) by Vivek-yadav01 · Pull Request #86 · Trisha-tech_OnlineBookSales - Google Chrome 5_15_2024 4_00_01 PM

**Pull request closed without merging**
