### PR TITLE
Animations Added

### PR DESCRIPTION
**Pull request by MHusain22**
# Description

I have added animations in the project using vanilla CSS.

Fixes:  #133 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Trisha-tech/OnlineBookSales/assets/118285713/394ceead-1998-4e8e-af85-1857a5ea481d

### CODE REVIEW

**Review by tushargupta1504 — APPROVED** [review]
good to go

**Comment by Trisha-tech** [comment]
@MHusain22 , Resolve these conflicts
screenshot-github com-2024 05 22-15_10_13

**Comment by MHusain22** [comment]
@Trisha-tech  It is not resolving I have tried many times but it will not affect the code and will work properly

**Comment by MHusain22** [comment]
@Trisha-tech I have resolved the conflicts now you can merge it.

**Pull request merged**
