### PR TITLE
Wishlist component

### LINKED ISSUE #179: Wishlist frontend + Backend[Feature Request]:
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So, when user visit the website and if he/she likes the book and wanted to buy afterwards then she can put the product into her wishlist.

### Use Case

when again user will visit to buy the product he/she can go into wishlist and buy the product instead of searching all over the website for the same product again

### Benefits

User convenience

### Add ScreenShots

WISHLIST_FEATURE_ISSUE

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sneha0019**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  -Adds the wishlist feature by integrating backend functionality.
  -Refactors the Shop page to include wishlist symbols.

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #179"

### Changes
List the detailed changes made in this PR.
-Added a new feature to our project for managing wishlists.
-Integrated backend endpoints for wishlist management.
-Updated the Shop page to display wishlist symbols.

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)

https://github.com/Trisha-tech/OnlineBookSales/assets/112338459/354b5b44-fb96-4f90-ac5c-cee190201e2e

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Sneha0019** [comment]
Hello, @Trisha-tech I've implemented the wishlist functionality, which required integrating backend endpoints for adding, fetching, and removing products from the wishlist. Additionally, I've made corresponding frontend updates, including logic adjustments and changes to the shop page to incorporate wishlist symbols.

Given the complexity and effort involved in implementing this feature, I would greatly appreciate your feedback on the code and changes made. 
Moreover, considering the challenges faced and the skills developed throughout this process, I respectfully request your consideration for an upgrade the label to Level 3 if you can. I believe this reflects the added responsibility and growth demonstrated in successfully completing this task.
Thank you for your time, guidance, and continuous support!

**Comment by Trisha-tech** [comment]
> ### Description
> A clear and concise description of what the PR does.
> 
> * This PR does the following:
>   -Adds the wishlist feature by integrating backend functionality.
>   -Refactors the Shop page to include wishlist symbols.
> 
> ### Related Issues
> Link any related issues using the format `Fixes #issue_number`. This helps to automatically close related issues when the PR is merged.
> 
> * Placeholder: "Fixes [Wishlist frontend + Backend[Feature Request]:  #179](https://github.com/Trisha-tech/OnlineBookSales/issues/179)"
> 
> ### Changes
> List the detailed changes made in this PR. -Added a new feature to our project for managing wishlists. -Integrated backend endpoints for wishlist management. -Updated the Shop page to display wishlist symbols.
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Run `npm install` to install dependencies.
> 3. Run `npm test` to execute the test suite.
> 4. Verify that ...
> 
> ### Screenshots (if applicable)
>  WISHLIST_FEATURE_RESOLVED.mp4 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

This is showing error
screenshot-localhost_3000-2024 06 25-12_32_31

**Comment by Sneha0019** [comment]
Hey, @Trisha-tech that error was due to login/logout functionality logic was not properly define Let me show you

Here below token was stored in localStorage
image

and during logout you were removing token from session storage instead of localstorage
image

Then I made changes in logout logic by putting localStorage instead of sessionStorage 
image

Also I made changes in navbar so when user is not logged in he/she will be redirected to login page 
image


Now I have made required changes so no errors will be show!  How should I make pull request to update changes in main repo..
Is it okay if I make a new issue. You can assign label of level1 there I can push all changes

Thank you!

**Comment by Sneha0019** [comment]
@Trisha-tech , please reply!

**Pull request merged**
