### PR TITLE
Issue#283 - User authentication (Sign up) successful

### LINKED ISSUE #283: Working on the user authentication in the sign up page
Currently the sign up page is not working. It is showing 'error occurred'. 
image
I would like to work on this issue. Please assign this to me.

### PR DESCRIPTION
**Pull request by Lanaanvar**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Fixes user authentication error during Sign up

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #283 "

### Changes
List the detailed changes made in this PR.
- Fixed a bug in Sign Up page due to multiple sending of tokens after signing up

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that valid MONGO_URL exists

### Screenshots (if applicable)
image
image
image

### Additional Context
Any additional context or information that reviewers should be aware of.
- After signing up, login in using the same email and password.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Trisha-tech** [comment]
> ### Description
> A clear and concise description of what the PR does.
> 
> * This PR does the following:
>   
>   * Fixes user authentication error during Sign up
> 
> ### Related Issues
> Link any related issues using the format `Fixes #issue_number`. This helps to automatically close related issues when the PR is merged.
> 
> * Placeholder: "Fixes [Working on the user authentication in the sign up page #283](https://github.com/Trisha-tech/OnlineBookSales/issues/283) "
> 
> ### Changes
> List the detailed changes made in this PR.
> 
> * Fixed a bug in Sign Up page due to multiple sending of tokens after signing up
> 
> ### Testing Instructions
> Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
> 
> 1. Pull this branch.
> 2. Run `npm install` to install dependencies.
> 3. Run `npm test` to execute the test suite.
> 4. Verify that valid MONGO_URL exists
> 
> ### Screenshots (if applicable)
> image image image
> 
> ### Additional Context
> Any additional context or information that reviewers should be aware of.
> 
> * After signing up, login in using the same email and password.
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly resolve these conflicts @Lanaanvar 
Update readme by NK-Works · Pull Request #363 · Trisha-tech_OnlineBookSales - Google Chrome 10_9_2024 6_32_20 PM

**Comment by Lanaanvar** [comment]
how do i resolve this issue? Not able to click the resolve conflict button

**Comment by Lanaanvar** [comment]
Is this okay?

**Comment by Suman373** [comment]
> Is this okay?

There is conflict in package lock file. You can remove your own package-lock and keep the updated one from the master branch.

**Review by Suman373 — COMMENTED** [review]
I am not able to understand where the bug was. 
1. Status code was changed
2. The response with customer object was changed

**Comment by Lanaanvar** [comment]
I'll explain the issue. When a customer signs up in the registration page, it shows : "An error occurred. Please try again later.". So I checked the backend code and found the problem that was causing this : The original code had multiple calls to sendToken(customer, 201, res). It was also sending multiple responses. So i did the following :

1. Removed the duplicate call to sendToken(customer, 201, res).
2. Only a single response is sent with all the required information, including the refreshToken, customer, and optional token.
3. Changed the status code from 404 to 400 for invalid requests, as it’s more appropriate for bad requests.
4. Explicitly included only necessary fields from the customer object in the response.

I hope this is understandable.

**Comment by Suman373** [comment]
> I'll explain the issue. When a customer signs up in the registration page, it shows : "An error occurred. Please try again later.". So I checked the backend code and found the problem that was causing this : The original code had multiple calls to sendToken(customer, 201, res). It was also sending multiple responses. So i did the following :
> 
>     1. Removed the duplicate call to sendToken(customer, 201, res).
> 
>     2. Only a single response is sent with all the required information, including the refreshToken, customer, and optional token.
> 
>     3. Changed the status code from 404 to 400 for invalid requests, as it’s more appropriate for bad requests.
> 
>     4. Explicitly included only necessary fields from the customer object in the response.
> 
> 
> I hope this is understandable.

Yes, this is comprehensive and understandable. Great work !! 👍
@Trisha-tech You may verify and merge

**Pull request merged**
