### PR TITLE
login-ui-updated

### PR DESCRIPTION
**Pull request by NK-Works**
### Description
I have updated the ui of the login page...
OLD UI: 
image image

NEW UI:
image  image

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by NK-Works** [comment]
I can also update the signup page if you can update the level...

**Comment by Trisha-tech** [comment]
> I can also update the signup page if you can update the level...

Create a new issue for the sign up page ui if you want to work on this @NK-Works

**Comment by Trisha-tech** [comment]
> ### Description
> I have updated the ui of the login page... OLD UI: image image
> 
> NEW UI: image image
> 
> ### Checklist
> Make sure to check off all the items before submitting. Mark with [x] if done.
> 
> * [x]  I have performed a self-review of my code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  My changes generate no new warnings
> * [x]  I am working on this issue under GSSOC

Kindly add the issue no you are addressing @NK-Works 
Good Work @NK-Works

**Comment by Suman373** [comment]
@NK-Works Create an issue regarding login UI update so that we can assign it to you!

**Comment by Suman373** [comment]
#289

**Review by Suman373 — COMMENTED** [review]
@Trisha-tech the CTA button after the "Don't have an account ? " feels out of place as using a link instead is conventional. Otherwise it is fine from my side.

**Comment by Trisha-tech** [comment]
> @Trisha-tech the CTA button after the "Don't have an account ? " feels out of place as using a link instead is conventional. Otherwise it is fine from my side.

Yes @Suman373, 
@NK-Works kindly replace that with simple link.

**Comment by NK-Works** [comment]
@Trisha-tech @Suman373 will change the button to link then...

**Comment by NK-Works** [comment]
image
image

i have change both the login and singup buttons to link... 
@Trisha-tech @Suman373 that should do it i guess...

**Comment by Suman373** [comment]
> image image
> 
> i have change both the login and singup buttons to link... @Trisha-tech @Suman373 that should do it i guess...

Yes it will. Great work ! 👍

**Comment by Trisha-tech** [comment]
Kindoyimage image
> 
> i have change both the login and singup buttons to link... @Trisha-tech @Suman373 that should do it i guess...

Kindly resolve these conflicts @NK-Works 
Screenshot_2024-10-05-19-00-43-022_com android chrome

**Comment by NK-Works** [comment]
@Trisha-tech now this branch doesn't have and problem you can merge now....

**Pull request merged**
