### PR TITLE
[Bug Fix] Fixed issue #542

### PR DESCRIPTION
**Pull request by poonam17122004**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Fixes the issue number #542 

### Changes
List the detailed changes made in this PR.

- updated  the dependency of useEffect hook in WhishList Screen which was causing a infinite loop. 

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by poonam17122004** [comment]
@Trisha-tech  Please review this PR.

**Comment by Suman373** [comment]
> @Trisha-tech Please review this PR.

Please recheck the issue # you have provided. We are not able to understand clearly what changes you have made.

**Comment by poonam17122004** [comment]
> > @Trisha-tech Please review this PR.
> 
> Please recheck the issue # you have provided. We are not able to understand clearly what changes you have made.

I am extremely sorry for that, I have resolved the issue number **542**


This the issue's link for your reference :- https://github.com/Trisha-tech/OnlineBookSales/issues/542

**Comment by poonam17122004** [comment]
@Suman373  Please review this PR

**Comment by Suman373** [comment]
> > > @Trisha-tech Please review this PR.
> > 
> > 
> > Please recheck the issue # you have provided. We are not able to understand clearly what changes you have made.
> 
> I am extremely sorry for that, I have resolved the issue number **542**
> 
> This the issue's link for your reference :- #542

No problem.

**Comment by Suman373** [comment]
@Trisha-tech You may verify and merge this PR.

**Pull request merged**
